<?php

/**
 * @file
 * Contains membership_offer.module.
 */

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function membership_offer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the membership_offer module.
    case 'help.page.membership_offer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Membership Offers') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function membership_offer_theme() {
  $theme = [];
  $theme['membership_offer'] = [
    'render element' => 'elements',
    'file' => 'membership_offer.page.inc',
    'template' => 'membership_offer',
  ];
  return $theme;
}
/**
 * Add membership offer base field to the Membership entity.
 *
 * Implements hook_entity_base_field_info().
 */
function membership_offer_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'membership') {
    $fields['membership_offer'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Membership Offer'))
      ->setDescription(t('The offer this membership fulfills.'))
      ->setRevisionable(TRUE)
      ->setSetting('target_type', 'membership_offer')
      ->setTranslatable(TRUE)
      ->setDisplayOptions('form', array(
        'type' => 'options_select',
        'weight' => 1,
      ))
      ->setDisplayConfigurable('form', TRUE)
      ->setRequired(TRUE)
      ->setDisplayConfigurable('view', TRUE);
  }
  return $fields;
}
